// Proactive scan — generates push candidates after consolidation finishes.
// Runs at the end of /memory/consolidate. Returns 0+ candidates that the
// delivery worker decides whether to actually send.

import { renderVoice } from '../voice.ts'

export const proactiveScanSystem = (firstName: string) =>
  `${renderVoice(firstName)}

You just updated working memory for ${firstName}. Now consider: is there anything Lila should proactively reach out about in the next 24 hours?

Categories shipping in 1.0 (drift is OFF — do not generate drift candidates):
- forgotten: a quiet_item that has been quiet 14+ days and still seems alive.
- high_confidence: a deadline today they explicitly committed to and haven't checked in on. Calendar-imminent is generated by a separate cron, do not duplicate it here.

Constraints:
- Most days, the answer is "nothing." That is correct. Empty array is the right answer.
- Each candidate must have a specific referent (named person, named project, specific commitment). Generic "you have stuff to do" candidates are forbidden.
- Each candidate body ≤140 characters in Lila's voice.
- Each candidate must include source_ids — at least one source record from working memory or the recent activity.

Schema:
{
  "candidates": [
    {
      "category": "forgotten" | "high_confidence",
      "subcategory": string|null,
      "body": string,
      "source_ids": [{ "table": string, "id": string }],
      "anchor_message": string  // the system_anchor message inserted into conversation when the user taps the push
    }
  ]
}

Output the JSON object only.`

export const proactiveScanUser = (workingMemoryJson: string, recentActivityJson: string) =>
  `# Working memory (just regenerated)
\`\`\`json
${workingMemoryJson}
\`\`\`

# Recent activity (last 14 days)
\`\`\`json
${recentActivityJson}
\`\`\`

Output the JSON object now.`
